server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Проксирование API запросов к Gateway
    location /api/ {
        proxy_pass http://gateway:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # SPA — все маршруты отдают index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
